"""Compile a verified plan to an execution artifact.

The full-scale run is Ibis-on-Spark inside an Argo Workflow. We *generate* the
artifact deterministically (safe YAML); actually submitting it needs a Spark +
Argo cluster and is out of scope for local verify. The generated workflow runs
the committed plan with the pinned ``covenant-transforms`` version, so what runs
at scale is exactly what local verify predicted.
"""

from __future__ import annotations

from typing import Any, Dict

import yaml

from .model import Plan

DEFAULT_IMAGE = "ghcr.io/covenant/runner:{version}"


def compile_argo(plan: Plan, plan_path: str, image: str | None = None) -> str:
    """Return an Argo Workflow YAML that runs *plan* on Spark via Ibis."""
    if not plan.conformance.ok:
        raise ValueError(
            "refusing to compile a plan that does not conform to its target contract; "
            f"problems: {plan.conformance.problems}"
        )
    product = plan.data_product.replace("/", "-")
    image = image or DEFAULT_IMAGE.format(version=plan.transforms_version)

    workflow: Dict[str, Any] = {
        "apiVersion": "argoproj.io/v1alpha1",
        "kind": "Workflow",
        "metadata": {"generateName": f"covenant-{product}-", "namespace": "covenant"},
        "spec": {
            "entrypoint": "run",
            "arguments": {
                "parameters": [
                    {"name": "plan", "value": plan_path},
                    {"name": "transforms-version", "value": plan.transforms_version},
                ]
            },
            "templates": [
                {
                    "name": "run",
                    "container": {
                        "image": image,
                        "command": ["python", "-m", "covenant.run"],
                        "args": ["--plan", "{{workflow.parameters.plan}}", "--backend", "spark"],
                        "resources": {"requests": {"cpu": "2", "memory": "4Gi"}},
                    },
                }
            ],
        },
    }
    header = (
        f"# Generated by Covenant from plan {plan.data_product!r} "
        f"(transforms {plan.transforms_version}). Do not edit by hand.\n"
        "# Full-scale run: Ibis-on-Spark. Only compiled from a contract-conformant plan.\n"
    )
    return header + yaml.safe_dump(workflow, sort_keys=False, default_flow_style=False)
