"""IR -> Apache Airflow DAG (Python).

Every user-controlled string is embedded with ``repr()`` (identifiers are also
validated upstream), so the generated module cannot be code-injected. Targets
Airflow 3 conventions: ``schedule=`` (not the deprecated ``schedule_interval``)
and per-task ``retries`` / ``execution_timeout`` taken from the IR rather than
hardcoded.
"""

from __future__ import annotations

import re
from typing import List

from ..ir import PipelineSpec, Task


def _timeout_seconds(timeout: str) -> int:
    m = re.match(r"^(\d+)([smhd]?)$", timeout.strip())
    if not m:
        return 0
    value, unit = int(m.group(1)), m.group(2)
    return value * {"": 1, "s": 1, "m": 60, "h": 3600, "d": 86400}[unit]


def _task_kwargs(tid: str, task: Task) -> List[str]:
    kwargs = [f"    task_id={tid!r},"]
    if task.retry:
        kwargs.append(f"    retries={task.retry.max_attempts},")
    if task.timeout:
        secs = _timeout_seconds(task.timeout)
        if secs:
            kwargs.append(f"    execution_timeout=timedelta(seconds={secs}),")
    if task.resources:
        # Airflow has no portable resource model for PythonOperator; record as doc.
        kwargs.append(f"    doc_md={_resource_doc(task)!r},")
    return kwargs


def _resource_doc(task: Task) -> str:
    parts = [f"{k}={v}" for k, v in sorted(task.resources.items())]
    return "FlowForge resources (not enforced by PythonOperator): " + ", ".join(parts)


def compile(spec: PipelineSpec) -> str:
    name = spec.metadata.name
    owner = spec.metadata.owner or "flowforge"
    schedule = spec.metadata.tags.get("schedule")  # cron string or None

    lines: List[str] = [
        f"# Generated by FlowForge from pipeline {name!r}. Do not edit by hand.",
        "from datetime import datetime, timedelta",
        "",
        "from airflow import DAG",
        "from airflow.operators.python import PythonOperator",
        "",
        "",
    ]

    # One callable stub per task. The real handler is referenced by name; the
    # body is a placeholder the user replaces with their task import.
    for tid, task in spec.tasks.items():
        lines.append(f"def _run_{tid}(**context):")
        doc = task.description or f"FlowForge task {tid}"
        lines.append(f"    {doc!r}")
        lines.append(f"    # handler: {task.handler.source}")
        lines.append("    raise NotImplementedError('wire this to your task implementation')")
        lines.append("")
        lines.append("")

    lines.append("with DAG(")
    lines.append(f"    dag_id={name!r},")
    lines.append(f"    default_args={{'owner': {owner!r}, 'retries': 0}},")
    lines.append("    start_date=datetime(2024, 1, 1),")
    lines.append(f"    schedule={schedule!r}," if schedule else "    schedule=None,")
    lines.append("    catchup=False,")
    lines.append(") as dag:")

    for tid, task in spec.tasks.items():
        lines.append(f"    {tid} = PythonOperator(")
        lines.append(f"        python_callable=_run_{tid},")
        for kw in _task_kwargs(tid, task):
            lines.append("    " + kw)
        lines.append("    )")
    lines.append("")

    # Dependencies as explicit set_upstream to keep output deterministic.
    for edge in spec.edges:
        lines.append(f"    {edge.to.task}.set_upstream({edge.from_.task})")

    return "\n".join(lines) + "\n"
