"""IR -> Argo Workflows YAML.

Emission goes through ``yaml.safe_dump`` (never f-string interpolation of user
values), so even if identifier validation were bypassed the output cannot be
injected. Output is deterministic (insertion order preserved, no key sorting)
so golden tests are stable.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List

import yaml

from ..ir import PipelineSpec, Task

DEFAULT_IMAGE = "python:3.11"


def _timeout_seconds(timeout: str) -> int:
    m = re.match(r"^(\d+)([smhd]?)$", timeout.strip())
    if not m:
        return 0
    value, unit = int(m.group(1)), m.group(2)
    return value * {"": 1, "s": 1, "m": 60, "h": 3600, "d": 86400}[unit]


def _container(task: Task) -> Dict[str, Any]:
    argo_cfg = task.executor_config.get("argo", {}) if task.executor_config else {}
    image = argo_cfg.get("image") or DEFAULT_IMAGE
    # The handler.source ("<pipeline>:<task>") is passed as an argument to a
    # generic runner entrypoint rather than interpolated into a shell string.
    container: Dict[str, Any] = {
        "image": image,
        "command": ["python", "-m", "flowforge_task"],
        "args": [task.handler.source],
    }
    if task.handler.env:
        container["env"] = [{"name": k, "value": v} for k, v in task.handler.env.items()]
    if task.resources:
        requests = {}
        if task.resources.get("cpu"):
            requests["cpu"] = task.resources["cpu"]
        if task.resources.get("memory"):
            requests["memory"] = task.resources["memory"]
        if requests:
            container["resources"] = {"requests": requests}
    return container


def compile(spec: PipelineSpec) -> str:
    name = spec.metadata.name
    deps: Dict[str, List[str]] = {tid: [] for tid in spec.tasks}
    for edge in spec.edges:
        if edge.to.task in deps:
            deps[edge.to.task].append(edge.from_.task)

    dag_tasks = []
    for tid in spec.tasks:
        entry: Dict[str, Any] = {"name": tid, "template": tid}
        if deps[tid]:
            entry["dependencies"] = deps[tid]
        dag_tasks.append(entry)

    templates: List[Dict[str, Any]] = [{"name": name, "dag": {"tasks": dag_tasks}}]

    for tid, task in spec.tasks.items():
        template: Dict[str, Any] = {"name": tid, "container": _container(task)}
        if task.timeout:
            secs = _timeout_seconds(task.timeout)
            if secs:
                template["activeDeadlineSeconds"] = secs
        if task.retry:
            template["retryStrategy"] = {"limit": task.retry.max_attempts}
            if task.retry.backoff and task.retry.backoff != "fixed":
                backoff: Dict[str, Any] = {"duration": f"{task.retry.initial_delay_seconds or 5}s"}
                if task.retry.backoff_multiplier:
                    backoff["factor"] = task.retry.backoff_multiplier
                template["retryStrategy"]["backoff"] = backoff
        templates.append(template)

    workflow: Dict[str, Any] = {
        "apiVersion": "argoproj.io/v1alpha1",
        "kind": "Workflow",
        "metadata": {"name": name, "namespace": "default"},
        "spec": {"entrypoint": name, "templates": templates},
    }
    header = f"# Generated by FlowForge from pipeline {name!r}. Do not edit by hand.\n"
    return header + yaml.safe_dump(workflow, sort_keys=False, default_flow_style=False, width=100)
